### ISSUE TITLE
Switch TeX math rendering engines for HTML

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#101]
From the beginning, we had the option of picking either MathJax or KaTeX.  We ended up picking MathJax because it had been around for more time, and because we couldn't evaluate performance requirements at that time.

However, we could now use a performance boost, and KaTeX might be faster than MathJax by a magnitude order.  So, I think that at this point we should evaluate the switch and make some experiments...

**Comment by aszasz** [comment]
I am commenting as you labeled it discussion: do we have an idea of how much time is spent on equations? If I make an experience of removing Chapter 6, 7 and 24 and measure process time will it give an idea about how much time can be saved with the switch?
For the rendering time on html, I think it would be even lowerest priority... something to worry for manu's evolution, not about the brt project.

**Comment by aszasz** [comment]
#107 logs: 
- [Only chapter 1](http://robrt.io/?https://brt.robrt.io/logs/1981d465/build.txt)
- [Removing chapters 6, 7 and 24](http://robrt.io/?https://brt.robrt.io/logs/a0c040f6/build.txt): from ``git  push <Enter>`` to slack notification: ``4'37''``
- [All-in](http://robrt.io/?https://brt.robrt.io/logs/c51dd948/build.txt): from ``git  push <Enter>`` to slack notification: ``7'04''``

Manu jumped from ``15''`` to ``80''`` (locally this was from ``7''`` to ``33''``)

(
LaTeX from ``3'02''`` to ``4'12''`` (locally this was from ``1'23''`` to ``2'00''``)
LFS needed more ``9''``
)

We jumped from 538 pdf pages to 793, i.e., roughly *50% more*

A guess I guess is safe on the side of potential maximum results (by assuming 50% more pdf pages would take 50% more time and that katex is 10 times faster) potential to gain would be gain ``50''`` in time that is going to end up being ``10'00''``.

_So in best case scenario, this is 10% boost. How much does it cost to get a hardware as powerful as my computer (a 4-year-old-Brazilian-market-i7-Dell)? Would that reduce time from ``10'`` back to ``6'``?_ 

As for browser _performânces_ :fr: 
The [fleet-size page](https://brt.robrt.io/branch/master/guide/service-planning/optimizing-vehicle-size-and-fleet-size.html) is among the heaviest on equations. It loads fast enough for me (refresh with ``shift+F5``), please check.

**Comment by jonasmalacofilho** [comment]
Indeed you have a good point!

It would probably be a small-*ish* improvement (10%).  But if we can find similar potential in other places, they all add up...

*Your computer is closer to a top of the line bare bones quad core Intel with fast SSD... And server hardware isn't considered that old after 3-4 years (specially CPUs).*

I'll keep this open but won't give too much priority to it, at least for the moment.

**Comment by jonasmalacofilho** [comment]
A [quick experiment](https://github.com/ITDP/the-online-brt-planning-guide/compare/master...jonasmalacofilho:use-katex-for-math?expand=1) shows that KaTeX is _much faster_ than MathJax, when used as engine for the math validation in manu: 485 ms against 16800 ms, of a total of 26505 ms for the complete run.

However, I still haven't been able to make that patch pass the unit tests and existing math in the Guide.

EDIT: note that things have changed these past few months and that now math validation is a major consumer of CPU time on the server.

**Comment by jonasmalacofilho** [comment]
While KaTeX retains the title of fastest engine, our build time with MathJax has been reduced by 75% after 67fe0662483cdd2e34d961646570c2586e1fea58.

We now spend no more than 5 seconds on validation, making this no longer a worthwhile endeavor.
