### ISSUE TITLE
Guide html main content slides under navigation/content menu

### ISSUE THREAD

**Issue by aszasz** [ITDP/the-online-brt-planning-guide#11]
Seen in Firefox and Chrome... if any guide page is zoomed in, and one rols the scrollbar(that appears in the bottom) to the right, the main content slides to the left (as expected), but the content/navigation menu does not move (as one, like me, might expect). The main content is being rendered behind the fixed content/navigation menu.

**Comment by aszasz** [comment]
The following unexpected behaviour seems to be related: if the window size is such that the there is a horizontal scroll bar (either because of zoom level or window horizontal size) when one clicks on a sub-subsection (expecting to have the begining of that subsection on the top of the screen), the main content area  is moved to the left (becaming partially under the content menu).
(Try, for instance select 9.7.1 and 9.7 back and forth with a small window)

**Comment by jonasmalacofilho** [comment]
Fixed in c64e73a8fae66963b37239dd3501bb52afc68fb9
