### ISSUE TITLE
Internet Explorer returns `undefined` for `document.baseURI`

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#116]
This breaks the nav bar loading.  `baseURI`, `<base>` or both are (at least partially) unsupported on IE 11.

**Comment by jonasmalacofilho** [comment]
It's been confirmed that `<base>` does work fine, and that the issue is only with `baseURI`.  Instead of filling it in, we're considering changing a bit how the end info (the relative url of the page) is obtained...

Currently, we generate `<base href="?">`.  Instead, we're thinking about generating `<base id="docbase" href="?" x-rel-path="?">` or something like that.  Then, in the client side JS, we'd switch to `var myUrl = J("base#docbase").attr("x-rel-path");`.

Implementation wise, `html.Generator.openBuffer` would receive a relative path and, internally, compute both the base `href` and `x-rel-path` attributes.

EDIT: `myUrl` should point to the page, not the dir; thus, changed `x-rel-dir` to `x-rel-path`.

**Comment by jonasmalacofilho** [comment]
Update: in the mean time, workaround in #117

**Comment by jonasmalacofilho** [comment]
Workaround merged into master and generally available.

Keeping this open while we improve the implementation...

**Comment by aszasz** [comment]
Will push following, but have not yet tested in IE.

**Comment by aszasz** [comment]
Implemented as conceived by @jonasmalacofilho in #121. As they say in stackoverflow:
>It worked like a charm
