### ISSUE TITLE
Uncontrolled overflow on heading

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#118]
All headings appear to the missing an explicit width.  One particular example: [section 1.5.1 – Listing of Benefits Commonly Sought with Major Public Transport Projects](https://brtguide.itdp.org/pull_request/117/guide/project-initiation/understanding-and-presenting-the-benefits.html#subSection.listing-of-benefits-commonly-sought-with-major-public-transport-projects).

Also, it's possible that more elements have the same issue, since `<p>`s appear to be inheriting the "correct width" from `.col-text` (via `margin-right`).

---

Commit: d2bbd7377f16e82d8c9e38308df44ec1d451eaca (head of 'master', as of now)

**Comment by craice** [comment]
This should work for the headings: https://github.com/ITDP/the-online-brt-planning-guide/pull/120

**Comment by jonasmalacofilho** [comment]
Closing, since other elements seem fine.

---

There is some weirdness with math, but that's something very specific and for another issue.  Also, it might be necessary to handle that properly when the current work on treating `DParagraph(HMath())` as a special case is complete.  (ping @aszasz)
