### ISSUE TITLE
When selecting subchapter in side content menu, borther chapters are unlisted

### ISSUE THREAD

**Issue by aszasz** [ITDP/the-online-brt-planning-guide#12]
If one selects a chapter, all subsections of the chapter, chapter under the same volume and all volumes  are listed (sons and brothers and uncles of selected).
But if one selects a subsection (beiing properly driven there), the list will include subsubsections (that are expanded), other subsections of the same chapter and all volumes, but not other chapters in the same volume... (sons, brothers, but no uncles... but showing great uncles).
Is that the expected behaviour?

**Comment by jonasmalacofilho** [comment]
No, that's a bug.

Issue confirmed.
