### ISSUE TITLE
Chapter 30 lacks an overview

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#142]
[Chapter 30 – Universal Access](https://brtguide.itdp.org/branch/master/guide/universal-access/) lacks an overview.

The first two paragraphs of the Introduction already describe the chapter are great candidates for it, but we would still be missing a quotation and some alternative opening text for the introduction.  Unless we were to move the entire introduction to the overview...

<details>
<summary>Progress</summary>

 - [x] make the overview from the first two paras of the intro
 - [x] delete the 30.1.1 heading and make it's content the intro
 - [ ] add a proper quotation for the overview

</details>

**Comment by aegauthier** [comment]
Ok - my recommendation would be to move the first paragraphs to the overview. I will look for another quote to go on the overview page (leave the Thoreau quote on the intro section. And then I would delete "30.1.1Who Benefits from Universal Access?" and just start with that text. It would change the numbering (and we could get rid of sub-section "30.1.1.1Not Just Wheelchairs" too.) - let me know if this is okay and I will start looking for a quote. Thanks.

**Comment by jonasmalacofilho** [comment]
I think it's fine too...

I went and made the fixes, it's just missing the new quotation.  
(for now I left the Thoreau quote duplicated... it's marked with a `\'FIXME'\` comment)

**Comment by jonasmalacofilho** [comment]
Oh, and thanks again for the awesomely quick help!  : )

**Comment by aszasz** [comment]
There are several quotes about the importance of the path/journey against the importance of destination, some quite poetical. I like the ones that talk about adjusting the path to reach a goal, and there is this one attributed to Columbus:
> By prevailing over all obstacles and distractions, one may unfailingly arrive at his chosen goal or destination.

**Comment by aszasz** [comment]
> Mind the gap

just occurred to me now!
