### ISSUE TITLE
Missing the contributors for a few chapters

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#143]
- [x] [Chapter 12 –Institutional Planning](https://brtguide.itdp.org/branch/master/guide/institutional-planning/)
 - [x] [Chapter 13 – Business Structure](https://brtguide.itdp.org/branch/master/guide/business-structure/)
 - [x] [Chapter 14 – Financial Modeling](https://brtguide.itdp.org/branch/master/guide/financial-modeling/)
 - [x] [Chapter 15 – Fare Policy and Structure](https://brtguide.itdp.org/branch/master/guide/fare-policy-and-structure/)
 - [x] [Chapter 16 – Informal Transit Transition to BRT](https://brtguide.itdp.org/branch/master/guide/informal-transit-transition-to-brt/)
 - [x] [Chapter 29 – Pedestrian Access](https://brtguide.itdp.org/branch/master/guide/pedestrian-access/)

**Comment by aegauthier** [comment]
Chapter 12: Walter Hook, BRT Planning International; Edgar Enrique Sandoval, consultant;

Chapter 13: Walter Hook, BRT Planning International; Gabriel Oliveira, ITDP Brasil; Iuri Moura, ITDP Brasil, Yoga Adiwinarto, ITDP Indonesia

Chapter 14: Diogo Barreto, LOGIT - Transportation Engineers

Chapter 15: Fabio Gordillo, GSD+

Chapter 16: Walter Hook, BRT Planning International; Colleen McCaul; Jonas Hagen

Chapter 29: Chris Kost, ITDP Africa; Shreya Gadepalli, ITDP India; Michael R. King, BuroHappold Engineering;

**Comment by jonasmalacofilho** [comment]
Fixed : )

Thanks, @aegauthier !
