### ISSUE TITLE
Make the overview pages more visually welcoming

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#176]
I'm going to document what we have discussed so far...

---

@aegauthier has raised the concern that the transition from the new cover page to the volume overviews is a bit sudden, in terms of the design.  We (myself, @craice and @aszasz ) agree with her.

---

Thus, we're working on trying to improve the volume overviews, without breaking the visual identify of the guide (since it would be very confusing for the reader to switch between different user interfaces all the time).  Also, we're concerned that the volume overviews can't look too different from the chapter overviews (which tend to resemble regular content and should not be overly polluted).

So far, we've experimented with, essentially, three ideas:

(a) adding a plain image (the same one from the cover, probably) to each volume overview, following the design applied to figures; however, there's no caption, and this might be confusing.

![009 1](https://user-images.githubusercontent.com/1832496/27277205-efd4a5b8-54b3-11e7-8b9e-47dd680cedca.png)

(b) imitating the banners from the cover page; this actually looks very nice, but isn't  compatible with the rest of the design (i.e. it looks very out of place when you look at pages other than the volume overviews).

![010](https://user-images.githubusercontent.com/1832496/27277305-39f0ce6a-54b4-11e7-83a7-76142e65fd18.png)

(c) doing something different, such as playing with color accents (instead of adding images); we're not happy with this particular example, but it gives an idea of where we were heading with this idea.

![014](https://user-images.githubusercontent.com/1832496/27277368-624cfeb0-54b4-11e7-99b8-ca74bead1589.png)

@aegauthier, can you let me know what you think of these mockups?

---

There are some potential ~technical~ maintenance concerns to address as well (i.e. it would be very bad for the editors if we ended up having 3 different places to change for each overview ... common stuff + HTML-only stuff + PDF-only stuff).

**Comment by aegauthier** [comment]
I am partial to options b and c. I get the idea that it looks a little out of place between the overview and the chapter pages, but I think it is okay as it is the link from the cover to the detail. But I also like c too.

By the way, I can't thank you all enough for this beautiful work. It is really amazing and I appreciate your thoughtfulness to both technical, grammatical : ), and aesthetic concerns. You guys are great.

**Comment by jonasmalacofilho** [comment]
alternative *b* implemented (PR #185) and deployed : )
