### ISSUE TITLE
nav: \subsubsection incorrect listing

### ISSUE THREAD

**Issue by craice** [ITDP/the-online-brt-planning-guide#196]
Incorrect listing of a `\subsubsection` in the `nav`.

**Comment by aszasz** [comment]
I can't confirm it...
... as far as I can tell it was reported after commit 04336ba2a8 and  was related to the nav showing sections 31.0.3 and 30.0.1 (not clear if 30.1 was displayed as 30.0.1).

**Comment by jonasmalacofilho** [comment]
The input that caused this was fixed in #194.  I'll try to isolate the issue in a reproduceable test.

**Comment by aszasz** [comment]
@jonas, that is very kind of you.

**Comment by jonasmalacofilho** [comment]
With `issue96.manu`

```
\volume{Volume Name}
\chapter{Chapter name}
\section{Section name}
\subsubsection{Sub-sub-section name}
```

run in a temporary folder:

```
manu gen issue196.manu .generated
http-server .generated/html -o -ext html
```

Then, check the nav at the section <http://127.0.0.1:8081/chapter-name/section-name>; it will show the sub-sub-section, but it shouldn't.

---

P.S. that is the _minimal_ test file, but it help you a lot to add

```
\html\store{<path>}\html\head{ <link rel="stylesheet" href="\$$assetPath(<path>)" /> }
```

at the beginning; `<path>` is the path to the guide's `style.css`.

**Comment by jonasmalacofilho** [comment]
Archiving: orphan sections will no longer reach the HTML generator (see #195).
