### ISSUE TITLE
Math inside boxes has overlay/zoom issues

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#208]
![screenshot from 2017-07-20 19-18-08](https://user-images.githubusercontent.com/1832496/28441255-45f2d3cc-6d80-11e7-803b-e38e6cab6062.png)

for comparison:

![screenshot from 2017-07-20 19-19-51](https://user-images.githubusercontent.com/1832496/28441299-743226ac-6d80-11e7-9f40-841020e8c84e.png)

**Comment by craice** [comment]
https://github.com/ITDP/the-online-brt-planning-guide/pull/209 - https://github.com/ITDP/the-online-brt-planning-guide/pull/209/commits/011caa815b3dd07193427021cf044303f5ac6449#diff-250e8ea0506a9f6f4a366f311e5c9ec0 - overflow.

[section 6.4 - box 6.2](https://brtguide.itdp.org/pull_request/209/guide/service-planning/optimizing-vehicle-size-and-fleet-size#box:how-to-determine-correction-factor-from-hour-to-cycle-time-phtocc-based-on-load-observations)
