### ISSUE TITLE
Web: zoom-able elements

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#26]
obviously:

- [x] figures
- [x] image based tables

maybe:

- ~other tables~
- [x] equations (math blocks)

**Comment by jonasmalacofilho** [comment]
@craice, can you "draw" the overlay zoomed elements?  At first, figures are enough; after that has implemented and tested, we can work on the other two...

**Comment by craice** [comment]
```
...
  <a id="..." class="overlay" style="display: none;">
    <img src="...">
  </a>
</body>
...
```

**Comment by aszasz** [comment]
@jonasmalacofilho, 
Equations, should be zoom-able? 
If so, is only to port the generation in a similar way of figures to equations... should I try to do it?
If not, just close this issue.

**Comment by jonasmalacofilho** [comment]
This issue was indeed outdated. #90 implemented zooming for figures and image tables.

Regular tables and equations could also benefit a bit from this, and the implementation would be somewhat similar.  However, it would be necessary to handle overflow (both vertical and horizontal) in a decent way, and I'm not sure how hard that would be.

_(marking the issue as low priority, as only support for figures (and image tables) was critical)_

**Comment by aszasz** [comment]
#124 addresses equations in an acceptable way 
If we intend to change for KaTex as proposed #101, it seems ok to merge it.

**Comment by jonasmalacofilho** [comment]
I don't think that zooming into regular tables makes that much sense anymore.  So I'm closing the issue, since everything else has already been implemented.
