### ISSUE TITLE
First item of a list with sub-list in a too narrow box 

### ISSUE THREAD

**Issue by aszasz** [ITDP/the-online-brt-planning-guide#3]
[here](https://brt.robrt.io/branch/development/guide/traffic-impact-assessment/-data-needs.html) the html render the bellow paragraph in two lines 
`<p>Classified vehicle turning movement counts at all the major intersections;</p>`
(CSS problem?)

**Comment by jonasmalacofilho** [comment]
ping @craice

**Comment by craice** [comment]
fixed. d7fb0f44
