### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#56]
A [favicon](https://en.wikipedia.org/wiki/Favicon)... EOM

**Comment by jonasmalacofilho** [comment]
@thaiscmlima, should it be the same used in the [itdp.org](https://www.itdp.org/wp-content/themes/itdp-responsive/images/favicon.ico) website?  If not, can you send us it in a common vector format (`.ai`, `.svg`)?

_(if you prefer, @craice can give you technical specs for the final – probably `.ico` – file)_

---

@craice, to avoid confusion, I was thinking about keeping the "official" favicon only for the master build; and using different ones for branch and pull request builds...  What do you think?  And what do you think we could use that would signal the build as non-master, at the same time keeping some relationship to the guide?

**Comment by craice** [comment]
@jonasmalacofilho we could use different colors for branch (gray) and pull requests (red) builds.

**Comment by thaiscmlima** [comment]
@jonasmalacofilho we can use our wheel as favicon, like in www.itdp.org

**Comment by thaiscmlima** [comment]
no different colors or modifications needed; just like it is ;-)

**Comment by jonasmalacofilho** [comment]
@thaiscmlima even if it isn't needed, _can_ we still use colors to differentiate the master branch (the official green) from other branches (gray) and pull requests (red), like @craice suggested?

**Comment by thaiscmlima** [comment]
ok!

**Comment by jonasmalacofilho** [comment]
great : )

we'll implement this soon...

**Comment by jonasmalacofilho** [comment]
Done : )
