### ISSUE TITLE
Git LFS rate limit for unauthenticated requests

### ISSUE THREAD

**Issue by lehonma** [ITDP/the-online-brt-planning-guide#88]
Github LFS has a limit for unauthenticated requests (60 requests/hour per IP) as seen here:
https://github.com/git-lfs/git-lfs/issues/797

It'll probably interfere with clone and pull operations

I think we should instruct our users to use ssh instead of https
e.g.:
```
git lfs clone git@github.com:protocubo/the-online-brt-planning-guide.git 
```
instead of 
```
git lfs clone https://github.com/protocubo/the-online-brt-planning-guide.git
```

**Comment by jonasmalacofilho** [comment]
Have we hit this already?

After reading the mentioned git-lfs issue I agree that we should document that it might be necessary to use authenticated requests for the upstream repository (this one), despite it being publicly accessible for reading.

However, https requests can be authenticated as well, and they're currently the most efficient protocol.  Further still, SSH on Windows might not be as easy for some users; sure, git-bash already includes a ssh client (right?), but users would still need to save (and protect) their private key, as well as register the corresponding public key on GitHub.

**Comment by lehonma** [comment]
Aimée and Daniel did.

I did read the documentation, but how can we **force** the user to clone our repo authenticated using https? (cause they 'can' clone our repo without authentication)

**Comment by aszasz** [comment]
I am registering here the command for https authenticated (Caio lehonma just told me)
```
 git clone https://username@github.com/username/repository.git

**Comment by aszasz** [comment]
Caio just tested clone with this setting. After including this in the readme page, I shall close the issue, if no further comments presented here.
