### ISSUE TITLE
Drop staging in 'development' and pull request directly against 'master'?

### ISSUE THREAD

**Issue by jonasmalacofilho** [ITDP/the-online-brt-planning-guide#99]
I'm thinking that having a staging "development" branch is a bit of overhead for the particular case of this project/repository: we _normally_ just want to keep the "master" (a.k.a the official) branch as up-to-date as possible.  _(the "master" is quite outdated right now, with no good reason like stability or version)_

Obviously there are moments were we might need a secondary branch to work on, like when we're dealing with a major change or don't want to risk the "master" branch going bad.  However, those instances (the days surrounding a particular release, or when a completely new edition is being worked on) seem rare in comparison with what we currently face. Also, for those rares times, we could create (and properly name) branches: "development-during-release" or "edition-33", for example.

What do you think (specifically @aszasz, but anyone else as well)?  Should we drop the "development" branch and work directly against the "master" branch (still using pull requests, of course)?

**Comment by BRTPlannerHelp** [comment]
Let's pull request to master directly... and give project/feature name to development(s) branch(es).
I considered opening this issue yesterday, but I would name it "Are there risks in pull request directly to master?", but I would like to do my homework before asking.

**Comment by jonasmalacofilho** [comment]
The default branch is now "master", which has been updated to point to the most recent "development".  All pull requests had their base changed to "master" as well.

The "development" branch will soon be deleted.
